micronaut:
  application:
    name: jewelryStorePipelineService
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
netty:
  default:
    allocator:
      max-order: 3
db:
  name: 'pipeline'
  collection: 'pipeline'
firestore:
  db:
    name: 'contact'
    collection: 'contact'
    url: ${FIRESTORE_URL:`https://contact.firebaseio.com`}
